### ISSUE TITLE
Implement exponential backoff for retries 

### ISSUE THREAD

**Issue by alovak** [moov-io/iso8583-connection#21]
Currently, we have a fixed wait time between reconnect. That’s not ideal and I think we should add exponential backoff (truncated) wait time before retries.

**Comment by sonalidbhavsar** [comment]
Hi @alovak , can you please assign this issue to me?

**Comment by alovak** [comment]
@sonalidbhavsar thanks for your participation!

do you need any additional information about this?

**Comment by adamdecaf** [comment]
We use a library in other code for this math
 https://github.com/sethvargo/go-retry/blob/main/backoff_exponential.go

**Comment by alovak** [comment]
closed by #66
