### ISSUE TITLE
Define how we extract requestID

### ISSUE THREAD

**Issue by jerome-laforge** [moov-io/iso8583-connection#40]
According to you, is it acceptable if I propose an PR where the `requestID` (currently given by https://github.com/moov-io/iso8583-connection/blob/fe9f74e6dba24076c443e23b10afff99b32e7e5a/connection.go#L457) can be overwritten via an option?

and by default, only stan will be used as `requestID`.

**Comment by alovak** [comment]
Not sure I understand the question, but this PR lets you to override how you generate request ID: https://github.com/moov-io/iso8583-connection/pull/39

**Comment by jerome-laforge** [comment]
Sorry, I miss this PR, but this is exactly what I am looking for :)
So i am waiting for a merge of this PR :)

Thanks again for your support

**Comment by jerome-laforge** [comment]
closed with #39 

many thx

**Comment by alovak** [comment]
here it is: https://github.com/moov-io/iso8583-connection/releases/tag/v0.3.2

**Comment by alovak** [comment]
@jerome-laforge join #iso8583 channel here https://slack.moov.io/ we can discuss different things/ideas/issues/approaches there if you want.
